### ISSUE TITLE
Swiping on Mobile creates a vertical scroll on the whole page

### ISSUE THREAD

**Issue by sharad-s** [goncy/react-swipy#2]
When implementing React-Swipy on mobile, the swipe will allow the user to drag the entire page up and down with their swipe. Is there a way to circumvent this?

**Comment by sharad-s** [comment]
This issue can be replicated by opening the codesandbox link on mobile: 

https://5x53pnrn3x.codesandbox.io/

**Comment by goncy** [comment]
Hi @sharad-s i think this is not library related, you could lock this behaviour disabling the overflows on the container or removing it's pointer events i think

**Comment by sharad-s** [comment]
Hi goncy, were you able to replicate this in the code sandbox on mobile?
The link I provided is the link to the demo of your own example on
Codesandbox.

If possible could you try to replicate this issue in your sandbox On mobile?
